service: node-annhyung
runtime: nodejs20
instance_class: F1
entrypoint: node src/bin/www.js

env_variables:
  NODE_ENV: 'production'
  PORT: 8080
  CLOUD_HOST: '34.64.248.193'
  CLOUDSQL_PORT: 5432
  CLOUDSQL_DB: 'postgres'
  CLOUDSQL_USER_CODELAB: 'codelab'
  CLOUDSQL_PASS_CODELAB: 'codelab1234'
  CODELAB_SCHEMA: 'hyung'
  DB_ROOT_CERT: certs/server-ca.pem
  DB_KEY: certs/client-key.pem
  DB_CERT: certs/client-cert.pem
  PRIVATE_IP: TRUE

handlers:
 - url: /.*
   script: auto
   secure: always
 
 - url: /public
   static_dir: /src/public

 - url: /dist
   static_dir: /src/dist





