service: node-annhyung
runtime: nodejs20
instance_class: F1
entrypoint: node src/bin/www.js

env_variables:
  NODE_ENV: 'production'
  PORT: 8080
  CLOUD_HOST: /cloudsql/winged-woods-442503-f1:asia-northeast3:codelab
  CLOUDSQL_PORT: 5432
  CLOUDSQL_DB: 'postgres'
  CLOUDSQL_USER_CODELAB: 'codelab'
  CLOUDSQL_PASS_CODELAB: 'codelab1234'
  CODELAB_SCHEMA: 'hyung'
  DB_ROOT_CERT: certs/server-ca.pem
  DB_KEY: certs/client-key.pem
  DB_CERT: certs/client-cert.pem
  PRIVATE_IP: TRUE

handlers:
 - url: /bldg/.*
   script: auto
   secure: always

 - url: /.*
   script: auto
   secure: always

 






