service: react-annhyung
runtime: nodejs20
instance_class: F1

env_variables:
  NODE_ENV: 'production'
  PORT: 8080
  CLOUD_HOST: ${CLOUD_HOST}
  CLOUDSQL_PORT: ${CLOUDSQL_PORT}
  CLOUDSQL_DB: ${CLOUDSQL_DB}
  CLOUDSQL_USER_CODELAB: ${CLOUDSQL_USER_CODELAB}
  CLOUDSQL_PASS_CODELAB: ${CLOUDSQL_PASS_CODELAB}
  CODELAB_SCHEMA: ${CODELAB_SCHEMA}
  DB_ROOT_CERT: certs/server-ca.pem
  DB_KEY: certs/client-key.pem
  DB_CERT: certs/client-cert.pem
  PRIVATE_IP: TRUE

handlers:
 - url: /api/.*
   script: auto
   secure: always

 - url: /bldg_map
   static_files: dist/index.html
   upload: dist/index.html
   secure: always


 - url: /
   static_files: dist/index.html
   upload: dist/index.html

 - url: /(.*\.(geojson|json|js|css|html|ico|png|jpg|jpeg|gif|svg|webp))
   static_files: dist/\1
   upload: dist/(.*\.(geojson|json|js|css|html|ico|png|jpg|jpeg|gif|svg|webp))$
   secure: always

